version: '3.9'
services:
  readme-notify-fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "readme-notify-fakesmtp"
    hostname: "readme-notify-fakesmtp"
    ports:
      - "8025:8025"
      - "1085:8080"

  readme-notify-rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme-notify-rabbitmq

    ports:
      - '1088:15672'
      - '5672:5672'

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  readme-notify-mongo:
    image: mongo:4.4
    container_name: readme-notify-mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    volumes:
      - readme-notify-mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme-notify-mongo-ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: readme-notify-mongo-ui

    ports:
      - ${MONGO_UI_PORT}:${MONGO_UI_PORT}

    environment:
      PORT: ${MONGO_UI_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme-notify-mongo:${MONGO_PORT}/

volumes:
    readme-notify-mongo:
